### ISSUE TITLE
devops

### ISSUE THREAD

**Issue by Lams364** [Lams364/ai-box#6]
In order to have good workflows, we need more devops tool implemented. 
Some things that would be nice to have.

- pre-commit git hook (lint, format, test) before each commit
- pipeline to test and deploy docker image in dockerhub or similar
- ...

**Comment by WingKwanChoi** [comment]
Pense tu d'ajouter les templates pour Issue et PR?

**Comment by Lams364** [comment]
> Pense tu d'ajouter les templates pour Issue et PR?

ouff, honnêtement on pourrait bien, mais j'ai pas de template en tête et me semble que je finis par toujours pas les utiliser. 

Though, si tu as l'habitude de travailler avec ça on peut le rajouter au billet et en créer un autre pour que tu fasse ça !! C'est certain que ça l'a une valeur ajouté

**Comment by WingKwanChoi** [comment]
ouais, je n'ai pas l'habitude de changer tout ce qui se trouve dans le template 😂, mais je pense que cela ajouterait de la valeur au projet et aussi c'est pas longue à faire. je vais ajouter un billet pour.
